name: Apolonia
favicon: null
layout_spectrum: 0.5613184876274318
typography_spectrum: 0.0653899044264108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e23'
    - '#989898'
    - '#2b3f95'
    - '#d8d8d8'
    - '#96261b'
  brandStrength: 0.9167308756150305
  lightness: 0.19764230819419026
  saturation: 0.5821484515909106
  rhythmicContrast: 0.4639045197982341
purpose: []
