name: Apolonia
favicon: null
layout_spectrum: 0.037121753208339214
typography_spectrum: 0.8609936540015042
title: Apolonia
description: Through My Eyes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.5455007455311716
  lightness: 0.13172860583290458
  saturation: 0.9511005282402039
  rhythmicContrast: 0.28955975105054677
purpose: []
