name: Apolonia
favicon: null
layout_spectrum: 0.57485
typography_spectrum: 0.6007
title: Apolonia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130000'
    - '#e2ab5c'
    - '#4e0300'
    - '#d08b35'
    - '#b75e10'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
