typography_spectrum: 0.6007
color:
  brandColors:
    - '#130000'
    - '#e2ab5c'
    - '#4e0300'
    - '#d08b35'
    - '#b75e10'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89984
analytics:
  google: null
  facebook: null
  twitter: null
name: Apolonia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Apolonia
description: Through My Eyes
purpose: []
